- name: deleting directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory

# - name: downloading and unzipping file
#   ansible.builtin.unarchive:
#     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
#     dest: "{{app_location}}"
#     remote_src: yes

- name: downloading artifact from nexus
  ansible.builtin.unarchive:
    src: http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip
    dest: "{{app_location}}"
    remote_src: yes